import { useEffect, useState } from 'react'
import { api } from '../api'
import type { ModelInfo } from '../api'

function MetricRow({ label, value, unit }: { label: string; value: string | number | null | undefined; unit?: string }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', borderBottom: '1px solid var(--border)' }}>
      <span style={{ color: 'var(--text-secondary)', fontSize: 10 }}>{label}</span>
      <span style={{ fontWeight: 700, fontSize: 11 }}>
        {value ?? '--'}{unit && value != null ? ` ${unit}` : ''}
      </span>
    </div>
  )
}

export function ModelEvaluationPage() {
  const [info, setInfo] = useState<ModelInfo | null>(null)

  useEffect(() => {
    api.modelInfo().then(setInfo).catch(() => setInfo(null))
  }, [])

  return (
    <div style={{ padding: 16 }}>
      <div className="card-title" style={{ fontSize: 14, marginBottom: 4 }}>Model Performance</div>
      <div style={{ color: 'var(--text-secondary)', fontSize: 11, marginBottom: 20 }}>
        Offline model evaluation — all metrics measured on synthetic test data generated by the same engine used for training.
        These metrics establish discriminability of simulator fault signatures and <strong>cannot be interpreted as real-world performance estimates</strong>.
      </div>

      <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
        {/* Isolation Forest */}
        <div className="card" style={{ flex: '1 1 260px' }}>
          <div className="card-title">Isolation Forest</div>
          <div style={{ color: '#0ea5e9', fontSize: 11, marginBottom: 10, fontWeight: 600 }}>
            Unsupervised Novelty Detection
          </div>
          <MetricRow label="Type" value={info?.isolation_forest.type} />
          <MetricRow label="Contamination" value={info?.isolation_forest.contamination} />
          <MetricRow label="N Estimators" value={info?.isolation_forest.n_estimators} />
          <MetricRow label="Empirical Threshold" value={info?.isolation_forest.threshold} />
          <MetricRow label="FP Rate (NORMAL data)" value="~0%" />
          <MetricRow label="Model Size" value={info?.isolation_forest.size_kb} unit="KB" />
          <div style={{ marginTop: 12, padding: '8px', background: 'rgba(14,165,233,0.06)', border: '1px solid rgba(14,165,233,0.15)', borderRadius: 5, fontSize: 9, color: 'var(--text-secondary)' }}>
            Threshold set at 1st percentile of normal validation scores — not sklearn default.
            Role: detect unknown anomalies the supervised models were not trained on.
          </div>
        </div>

        {/* XGBoost */}
        <div className="card" style={{ flex: '1 1 260px' }}>
          <div className="card-title">XGBoost Fault Classifier</div>
          <div style={{ color: '#f97316', fontSize: 11, marginBottom: 10, fontWeight: 600 }}>
            Supervised Tabular Classification
          </div>
          <MetricRow label="Type" value={info?.xgboost.type} />
          <MetricRow label="Max Depth" value={info?.xgboost.max_depth} />
          <MetricRow label="N Estimators" value={info?.xgboost.n_estimators} />
          <MetricRow label="Test Accuracy (synthetic)" value={info?.xgboost.test_accuracy ? `${(info.xgboost.test_accuracy * 100).toFixed(0)}%` : '--'} />
          <MetricRow label="Model Size" value={info?.xgboost.size_kb} unit="KB" />
          <div style={{ marginTop: 12 }}>
            <div style={{ fontSize: 9, color: 'var(--text-secondary)', marginBottom: 6 }}>Classes (8):</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
              {(info?.xgboost.classes ?? []).map(c => (
                <span key={c} className="badge badge-info" style={{ fontSize: 8 }}>{c}</span>
              ))}
            </div>
          </div>
          <div style={{ marginTop: 12, padding: '8px', background: 'rgba(249,115,22,0.06)', border: '1px solid rgba(249,115,22,0.15)', borderRadius: 5, fontSize: 9, color: 'var(--text-secondary)' }}>
            Ablation: XGBoost (89%) vs Random Forest (87.5%) vs Decision Tree-3 (91%) on same splits.
            XGBoost selected for native NaN handling (SENSOR_DROPOUT) and feature importance output.
          </div>
        </div>

        {/* CNN */}
        <div className="card" style={{ flex: '1 1 260px' }}>
          <div className="card-title">Temporal 1D CNN</div>
          <div style={{ color: '#a855f7', fontSize: 11, marginBottom: 10, fontWeight: 600 }}>
            Supervised Temporal Classification (ONNX)
          </div>
          <MetricRow label="Type" value={info?.cnn.type} />
          <MetricRow label="In Channels" value={info?.cnn.in_channels} />
          <MetricRow label="Num Classes" value={info?.cnn.num_classes} />
          <MetricRow label="Test Accuracy (synthetic)" value={info?.cnn.test_accuracy ? `${(info.cnn.test_accuracy * 100).toFixed(0)}%` : '--'} />
          <MetricRow label="Host Inference Latency" value={info?.cnn.host_latency_ms} unit="ms (Windows x86)" />
          <MetricRow label="Total ONNX Size" value={info?.cnn.size_kb} unit="KB" />
          <div style={{ marginTop: 12, padding: '8px', background: 'rgba(168,85,247,0.06)', border: '1px solid rgba(168,85,247,0.15)', borderRadius: 5, fontSize: 9, color: 'var(--text-secondary)' }}>
            BatchNorm1D on input channels eliminates scale-dominance artefacts (improved 76%→99% on synthetic test set).
            Advantage over XGBoost: raw temporal waveform for transient IMPACT_LIKE_EVENT events.
          </div>
        </div>
      </div>

      <div style={{ marginTop: 16 }} className="card">
        <div className="card-title">Ablation Summary — Classifier Comparison</div>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--border)' }}>
                {['Model', 'Test Accuracy (Synthetic)', 'NaN Handling', 'Feature Importance', 'Notes'].map(h => (
                  <th key={h} style={{ textAlign: 'left', padding: '6px 8px', color: 'var(--text-secondary)', fontWeight: 600, fontSize: 9, textTransform: 'uppercase', letterSpacing: '0.08em' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {[
                ['Decision Tree (depth=3)', '91%', '✗', '✓', 'Overfits to NaN flags; no probability output'],
                ['Random Forest (n=50)', '87.5%', '✗', '✓', 'Slower, no NaN support'],
                ['XGBoost (selected)', '89%', '✓', '✓', 'Native NaN, probability calibration, 341KB'],
              ].map(([model, acc, nan, fi, note]) => (
                <tr key={model as string} style={{ borderBottom: '1px solid rgba(30,45,69,0.5)' }}>
                  <td style={{ padding: '6px 8px', fontWeight: model === 'XGBoost (selected)' ? 700 : 400, color: model === 'XGBoost (selected)' ? '#f97316' : 'var(--text-primary)' }}>{model}</td>
                  <td style={{ padding: '6px 8px', color: '#22c55e' }}>{acc}</td>
                  <td style={{ padding: '6px 8px' }}>{nan}</td>
                  <td style={{ padding: '6px 8px' }}>{fi}</td>
                  <td style={{ padding: '6px 8px', color: 'var(--text-dim)', fontSize: 9 }}>{note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
